### ISSUE TITLE
Rule Ref in docs is incorrect

### ISSUE THREAD

**Issue by PaulREnglish** [bigbite/phpcs-config#63]
**Describe the bug**  
PHPCS can't find the sniffs when following the instructions in the docs.  This is because the instructions in the docs say this:
```
<?xml version="1.0"?>
<ruleset name="{PROJECT} Rules">
	<rule ref="BigBite" />
</ruleset> 
```

When using the above in my phpcs file, I get an error message telling me that the sniff does not exist:
![](http://bigbite.im/i/p14SNH+)

I think the ruleset in the docs is supposed to be:
```
<?xml version="1.0"?>
<ruleset name="WP Slack Notifications Rules">
	<rule ref="./vendor/bigbite/phpcs-config/BigBite" />
</ruleset>
```
When I run phpcs using the above, everything works fine.

**To Reproduce**  
1.  Follow the instructions in the readme.
2. Run PHPCS (I used the terminal to do this), you'll get this error message http://bigbite.im/i/p14SNH

**Expected behaviour**  
All the sniffs should run and there should be no error message.

**Screenshots**  
Screenshot of error message:
![](http://bigbite.im/i/p14SNH+)

**Platform**  
- OS: macOS
- Shell: zsh

**Additional Context**
I've only tested the problem using the prefab-plugin-template which installs this repo automatically.

**Comment by jonmcp** [comment]
Thanks @PaulREnglish 
Yeah the docs show the ruleset as though the package has been installed globally, despite the installation instructions being project-level.
